import vue from "@vitejs/plugin-vue";
import { defineConfig } from "vitest/config";

// Unit + component tests. E2E (Playwright, #13) lives outside this config and
// deliberately does not contribute to coverage — it measures flows, not lines.
export default defineConfig({
  plugins: [vue()],
  test: {
    environment: "jsdom",
    include: ["src/**/*.spec.ts"],
    coverage: {
      provider: "v8",
      // Every source file is reported, not just the ones a test imported
      // (Vitest 4 does this by default for files matching `include`).
      include: ["src/**/*.{ts,vue}"],
      exclude: [
        "src/main.ts", // bootstrap
        "src/**/*.gen.ts", // generated by tauri-specta
        "src/**/*.d.ts",
        "src/**/*.spec.ts",
      ],
      reporter: ["text", "lcov"],
      // PROJECT.md §4: 100% for the logic layers, 90% for UI components.
      // Thresholds are per glob group; a layer with no files yet simply has
      // nothing to fail on, and starts being enforced the day it gets one.
      thresholds: {
        "src/core/**": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/profiles/**": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/features/registry.ts": { lines: 100, branches: 100, functions: 100, statements: 100 },
        "src/features/**/*.vue": { lines: 90, branches: 90, functions: 90, statements: 90 },
        "src/controls/**": { lines: 90, branches: 90, functions: 90, statements: 90 },
        "src/screens/**/*.vue": { lines: 90, branches: 90, functions: 90, statements: 90 },
        "src/App.vue": { lines: 90, branches: 90, functions: 90, statements: 90 },
      },
    },
  },
});
