// Generated by tauri-specta from Rust. Do not edit — run `make gen`.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  The startup question: is the backend usable, and if not, which screen says
	 *  why. Returns a verdict rather than a `Result` — "it does not work" is the
	 *  answer here, not an error.
	 */
	detectBinary: () => __TAURI_INVOKE<Detection>("detect_binary"),
	listDevices: () => typedError<Device[], BackendError>(__TAURI_INVOKE("list_devices")),
	deviceState: (deviceId: string) => typedError<DeviceState, BackendError>(__TAURI_INVOKE("device_state", { deviceId })),
	setParam: (deviceId: string, param: string, value: ParamValue) => typedError<null, BackendError>(__TAURI_INVOKE("set_param", { deviceId, param, value })),
};

/* Types */
export type BackendError = 
/**
 *  The backend does not implement this operation. Part of the wire contract
 *  (the frontend already renders it) for a backend that covers only part of
 *  the seam — the planned native HID one, for instance.
 */
{ kind: "not_implemented" } | 
/**  The operation reached the device layer and failed there. */
{ kind: "failed"; message: string };

export type Battery = {
	status: BatteryStatus,
	/**  Percentage; only meaningful when the status is `Available`. */
	level: number | null,
};

export type BatteryStatus = "available" | "charging" | "unavailable";

/**
 *  What the startup probe concluded. Each variant is a state of the frontend's
 *  state machine, so this type *is* the detection contract with the UI.
 */
export type Detection = 
/**  A usable binary; the devices it reports can be read. */
{ kind: "ready" } | 
/**  Nothing to run — not installed, or not on `PATH`. */
{ kind: "missing_binary" } | 
/**
 *  A binary that is too old, or one whose output this app cannot read at
 *  all. `found` is `None` in the second case: an incompatible binary is a
 *  clear screen rather than an invented version number.
 */
{ kind: "bad_version"; found: string | null; required: string } | 
/**
 *  The binary works and lists devices, but every one of them refuses to
 *  open — the udev rule is missing.
 */
{ kind: "no_permissions" };

/**
 *  A headset (or its dongle) as the UI knows it.
 * 
 *  `capabilities` are the raw `CAP_*` identifiers reported by the device. They
 *  stay strings on purpose: a newer `headsetcontrol` may report a capability
 *  this build has never heard of, and the frontend has to ignore it rather than
 *  fail to read the device (forward compatibility, PROJECT.md §3.3).
 */
export type Device = {
	/**  Stable identity across hotplug events: `"{vendor_id:04x}:{product_id:04x}"`. */
	id: string,
	name: string,
	vendor: string,
	product: string,
	vendorId: number,
	productId: number,
	capabilities: string[],
};

/**
 *  Live values of a device. Every field is optional — a device reports only
 *  what its capabilities cover.
 */
export type DeviceState = {
	battery: Battery | null,
	chatmix: number | null,
};

/**
 *  Value written to a device parameter. Parameters are addressed by their
 *  capability identifier, so supporting a new one needs no change here.
 */
export type ParamValue = { kind: "int"; value: number } | { kind: "bool"; value: boolean };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

