// Generated by tauri-specta from Rust. Do not edit — run `make gen`.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listDevices: () => typedError<Device[], BackendError>(__TAURI_INVOKE("list_devices")),
	deviceState: (deviceId: string) => typedError<DeviceState, BackendError>(__TAURI_INVOKE("device_state", { deviceId })),
	setParam: (deviceId: string, param: string, value: ParamValue) => typedError<null, BackendError>(__TAURI_INVOKE("set_param", { deviceId, param, value })),
};

/* Types */
export type BackendError = 
/**
 *  The backend does not implement this operation. Part of the wire contract
 *  (the frontend already renders it) for a backend that covers only part of
 *  the seam — the planned native HID one, for instance.
 */
{ kind: "not_implemented" } | 
/**  The operation reached the device layer and failed there. */
{ kind: "failed"; message: string };

export type Battery = {
	status: BatteryStatus,
	/**  Percentage; only meaningful when the status is `Available`. */
	level: number | null,
};

export type BatteryStatus = "available" | "charging" | "unavailable";

/**
 *  A headset (or its dongle) as the UI knows it.
 * 
 *  `capabilities` are the raw `CAP_*` identifiers reported by the device. They
 *  stay strings on purpose: a newer `headsetcontrol` may report a capability
 *  this build has never heard of, and the frontend has to ignore it rather than
 *  fail to read the device (forward compatibility, PROJECT.md §3.3).
 */
export type Device = {
	/**  Stable identity across hotplug events: `"{vendor_id:04x}:{product_id:04x}"`. */
	id: string,
	name: string,
	vendor: string,
	product: string,
	vendorId: number,
	productId: number,
	capabilities: string[],
};

/**
 *  Live values of a device. Every field is optional — a device reports only
 *  what its capabilities cover.
 */
export type DeviceState = {
	battery: Battery | null,
	chatmix: number | null,
};

/**
 *  Value written to a device parameter. Parameters are addressed by their
 *  capability identifier, so supporting a new one needs no change here.
 */
export type ParamValue = { kind: "int"; value: number } | { kind: "bool"; value: boolean };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

