//! Thin IPC commands — the only Rust surface the frontend can call.
//!
//! Commands stay free of logic: they delegate to the [`HeadsetBackend`] behind
//! the app's managed state and return domain types whose TypeScript
//! counterparts are generated by tauri-specta.
//!
//! Excluded from the Rust coverage gate on purpose (see
//! `scripts/rs-coverage-gate.mjs`): there is nothing here to unit-test that the
//! backend's own tests do not already cover, and the real IPC path is exercised
//! by the smoke E2E suite (#14).

use tauri::State;

use crate::backend::{BackendError, Device, DeviceState, HeadsetBackend, ParamValue};

/// The backend implementation the app runs against, managed by Tauri.
pub struct Backend(pub Box<dyn HeadsetBackend>);

#[tauri::command]
#[specta::specta]
pub fn list_devices(backend: State<'_, Backend>) -> Result<Vec<Device>, BackendError> {
    backend.0.list_devices()
}

#[tauri::command]
#[specta::specta]
pub fn device_state(
    backend: State<'_, Backend>,
    device_id: String,
) -> Result<DeviceState, BackendError> {
    backend.0.device_state(&device_id)
}

#[tauri::command]
#[specta::specta]
pub fn set_param(
    backend: State<'_, Backend>,
    device_id: String,
    param: String,
    value: ParamValue,
) -> Result<(), BackendError> {
    backend.0.set_param(&device_id, &param, value)
}
