//! Thin IPC commands — the only Rust surface the frontend can call.
//!
//! Commands stay free of logic: they delegate to the [`HeadsetBackend`] behind
//! the app's managed state and return domain types whose TypeScript
//! counterparts are generated by tauri-specta.
//!
//! Every one of them is `#[tauri::command(async)]`. A command without it runs on
//! the **main thread**, and each of these blocks on a `headsetcontrol` process:
//! with the refresh loop calling in every 5 s (`src/core/refresh.ts`) that would
//! stall the event loop on a cadence, and a headset asleep behind its dongle
//! makes the wait seconds long. `async` moves them onto Tauri's pool instead;
//! `backend/exec.rs` bounds how long any one of them can take.
//!
//! Excluded from the Rust coverage gate on purpose (see
//! `scripts/rs-coverage-gate.mjs`): there is nothing here to unit-test that the
//! backend's own tests do not already cover, and the real IPC path is exercised
//! by the smoke E2E suite (#14).

use std::sync::Arc;

use tauri::State;

use crate::backend::{BackendError, Detection, Device, DeviceState, HeadsetBackend, ParamValue};

/// The backend implementation the app runs against, managed by Tauri. Shared
/// rather than owned: the hotplug watcher lists devices through the same one.
pub struct Backend(pub Arc<dyn HeadsetBackend>);

/// The startup question: is the backend usable, and if not, which screen says
/// why. Returns a verdict rather than a `Result` — "it does not work" is the
/// answer here, not an error.
#[tauri::command(async)]
#[specta::specta]
pub fn detect_binary(backend: State<'_, Backend>) -> Detection {
    backend.0.detect()
}

#[tauri::command(async)]
#[specta::specta]
pub fn list_devices(backend: State<'_, Backend>) -> Result<Vec<Device>, BackendError> {
    backend.0.list_devices()
}

#[tauri::command(async)]
#[specta::specta]
pub fn device_state(
    backend: State<'_, Backend>,
    device_id: String,
) -> Result<DeviceState, BackendError> {
    backend.0.device_state(&device_id)
}

#[tauri::command(async)]
#[specta::specta]
pub fn set_param(
    backend: State<'_, Backend>,
    device_id: String,
    param: String,
    value: ParamValue,
) -> Result<(), BackendError> {
    backend.0.set_param(&device_id, &param, value)
}
