//! Thin IPC commands — the only Rust surface the frontend can call.
//!
//! Commands stay free of logic: they delegate to [`crate::backend`] and return
//! domain types whose TypeScript counterparts are generated by tauri-specta.
//!
//! Populated in #4 (core seams: type generation, backend.ts, MockBackend).
