//! Application wiring: plugins, IPC handlers, Tauri builder.
//!
//! Kept free of headset domain logic — that lives in [`backend`], exposed to the
//! frontend through the thin commands in [`commands`].

mod backend;
mod commands;

use tauri_specta::{Builder, collect_commands};

/// The single description of the IPC surface: it registers the commands with
/// Tauri **and** generates their TypeScript counterparts, so the two can never
/// disagree. Regenerate with `make gen`.
fn ipc() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::list_devices,
        commands::device_state,
        commands::set_param,
    ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let ipc = ipc();

    tauri::Builder::default()
        .plugin(tauri_plugin_log::Builder::new().build())
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_notification::init())
        .invoke_handler(ipc.invoke_handler())
        .manage(commands::Backend(Box::new(backend::UnimplementedBackend)))
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod export {
    use super::ipc;
    use specta_typescript::Typescript;

    /// Not a test of behaviour — this is `make gen`. Keeping generation in a
    /// test means CI regenerates the bindings on every run and a stale
    /// `types.gen.ts` shows up as a dirty working tree.
    #[test]
    fn export_typescript_bindings() {
        ipc()
            .export(
                Typescript::default().header(
                    "// Generated by tauri-specta from Rust. Do not edit — run `make gen`.",
                ),
                "../src/core/types.gen.ts",
            )
            .expect("failed to export TypeScript bindings");
    }
}
