//! Application wiring: plugins, IPC handlers, Tauri builder.
//!
//! Kept free of headset domain logic — that lives in [`backend`], exposed to the
//! frontend through the thin commands in [`commands`].

mod backend;
mod commands;

use std::sync::Arc;

use tauri::{AppHandle, Emitter};
use tauri_specta::{Builder, collect_commands};

use backend::hotplug::{self, ChangeSink};

/// The single description of the IPC surface: it registers the commands with
/// Tauri **and** generates their TypeScript counterparts, so the two can never
/// disagree. Regenerate with `make gen`.
fn ipc() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::detect_binary,
        commands::list_devices,
        commands::device_state,
        commands::set_param,
    ])
}

/// Carries a hotplug change to the webview. The event has no payload: the
/// frontend re-lists devices when it arrives (#10).
struct WebviewEvents(AppHandle);

impl ChangeSink for WebviewEvents {
    fn devices_changed(&self) {
        if let Err(error) = self.0.emit(hotplug::DEVICES_CHANGED, ()) {
            log::warn!("could not deliver a hotplug event: {error}");
        }
    }
}

/// Starts watching for hotplug on its own thread: the watchers block, and the
/// UI thread must not.
fn watch_devices(app: &AppHandle, backend: Arc<dyn backend::HeadsetBackend>) {
    let forced = hotplug::forces_polling(std::env::var(hotplug::WATCHER_ENV).ok().as_deref());
    let watcher = hotplug::choose(forced, backend::native_watcher, || backend::PollingWatcher);
    let events = WebviewEvents(app.clone());

    std::thread::spawn(move || hotplug::watch(watcher, move || backend.list_devices(), events));
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let ipc = ipc();
    // The real adapter, with both of its impure edges plugged in: the process
    // spawn and the look at device nodes (#8, #9). Shared, because the hotplug
    // thread lists devices through the same backend the commands use.
    let backend: Arc<dyn backend::HeadsetBackend> = Arc::new(backend::HeadsetControlBackend::new(
        backend::ProcessRunner::new(),
        backend::HidrawAccess,
    ));
    let watched = Arc::clone(&backend);

    tauri::Builder::default()
        .plugin(tauri_plugin_log::Builder::new().build())
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_notification::init())
        .invoke_handler(ipc.invoke_handler())
        .manage(commands::Backend(backend))
        .setup(move |app| {
            watch_devices(app.handle(), watched);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

#[cfg(test)]
mod export {
    use super::ipc;
    use specta_typescript::Typescript;

    /// Not a test of behaviour — this is `make gen`. Keeping generation in a
    /// test means CI regenerates the bindings on every run and a stale
    /// `types.gen.ts` shows up as a dirty working tree.
    #[test]
    fn export_typescript_bindings() {
        ipc()
            .export(
                Typescript::default().header(
                    "// Generated by tauri-specta from Rust. Do not edit — run `make gen`.",
                ),
                "../src/core/types.gen.ts",
            )
            .expect("failed to export TypeScript bindings");
    }
}
